name:                pi-calc-lts
version:             0.1.0.0
github:              "githubuser/pi-calc-lts"
license:             BSD3
author:              "Aina Centelles Tarrés"
maintainer:          "ac2009@hw.ac.uk"
copyright:           "2022 Aina Centelles Tarrés"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/pi-calc-lts#readme>

dependencies:
- base >= 4.7 && < 5
- nom
- syb
- containers
- Stream

library:
  source-dirs: src

executables:
  pi-calc-lts-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pi-calc-lts
    - containers
    - syb
    - nom
    - base >= 4.7 && < 5
    - Stream

tests:
  pi-calc-lts-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pi-calc-lts
    - containers
    - syb
    - nom
    - base >= 4.7 && < 5
    - Stream
    - QuickCheck
    - hspec
