name:                pi-calc-lts
version:             0.1.0.0
github:              "ainac99/pi-calc-lts"
license:             MIT
author:              "Aina Centelles Tarrés"
maintainer:          "ainac99@gmail.com"
copyright:           "2022 Aina Centelles Tarrés"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/ainac99/pi-calc-lts#readme>

dependencies:
- base >= 4.7 && < 5
- nom
- syb
- containers
- Stream

library:
  source-dirs: src

executables:
  pi-calc-lts-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pi-calc-lts
    - containers
    - syb
    - nom
    - base >= 4.7 && < 5
    - Stream

tests:
  pi-calc-lts-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pi-calc-lts
    - containers
    - syb
    - nom
    - base >= 4.7 && < 5
    - Stream
    - QuickCheck
    - hspec
